### PR TITLE
Updates the generic selector example in the README.md file.

### PR DESCRIPTION
**Pull request by fsamapoor**
Fixes the generic selector usage examples.

References: https://github.com/GuavaCZ/tutorials/issues/5

### CODE REVIEW

**Comment by lukas-frey** [comment]
Hi, thanks a lot, Faraz! Merging.

**Comment by fsamapoor** [comment]
> Hi, thanks a lot, Faraz! Merging.

Hey Lukas,

Great job on the plugin! I've started using it in one of my projects, and it seems really promising. I'm going to improve it as much as I can because I think it has a lot of potential and plenty of areas to enhance. Thank you for the brilliant idea!

**Comment by lukas-frey** [comment]
Thanks a lot, Faraz! I really appreciate that, as I currently don't have much time to improve upon it, so your proposal it is very welcome.

I'm aware that the plugin has quite a few shortcomings and could be improved, I initially hoped I'd be able to refactor it into a v2.0 version, but right now I have to postpone it.

If you run into any issues though, feel free to create an issue and I'll do my best to assist. :)

**Comment by fsamapoor** [comment]
@lukas-frey Thank you. Will do my best to propose changes with the possible issues as a PR.

**Pull request merged**
